sudo: required
language: generic
services: docker
env:
- HHVM_VERSION=4.25-latest
- HHVM_VERSION=latest
- HHVM_VERSION=nightly
install:
- docker pull hhvm/hhvm:$HHVM_VERSION
script:
- docker run --rm -w /var/source -v $(pwd):/var/source hhvm/hhvm:$HHVM_VERSION ./.travis.sh
notifications:
  slack:
    secure: NzOQEd043YXWNPXrwYQLOZM86g3vHdJWNLtyXXSrGEH6565e62EaSfjmDldubnlwdVLBxAfF2JPAAcWgBpOZd3w3zF6+sKz/rl2fbOfHDEixLAEnpn9mqX6AYjs7/nj8+6nxeG5Vgjpy4FDCArQDwI6iTjohtyWFMYWmim90DfPNjZNijRt0P6wwPSJCTA9bH8bSHgiHr8cfVhGE2PQ0pNgeSWGSLLtrbrv8PJoVf15zW/I/CTMUHxEG7fd52YCqenk9ksnY1JZWbFamFFHUGJfHHAhsD5/O72r40CWJzC7o4dkOovup5plaJ4WhpYrBWKYIrXui3Ql98Dk7P0O3TBJc8K3ASpkBfiPR9sBvVu9HKOiZlD8fCXoFagrQSzXyYnKPJvI4sm546Evd1nx6iVDf2u11+hNzJKGp4wyzbkjOZjUgQI4rGuC34iPYUX8lTfzjJ2HDwKd3dQ2wa3FxcQX/e1r3cK+e7TahMFHZb1axn0Z83jK8Dh8NBnonjoK3pGgozqlWQlRlz7rxPair8OMVGFJ2jj0KAxEP0/uPtJgKy8LPt+m3haXO0FFZOFn3zkVPP/YDKOGmaaeaH3TTPPOq1MG0qnbcICRUH2/eJ0Rj8Uagxi7qW+VVC96pVkeBvDp9ULFDLFj0+AY49Do678QGijBMOyriwb5sRcGT7oQ=
